@echo off
echo Starting CortexDesk...
echo.
echo Starting Backend API...
start cmd /k "cd /d "%~dp0" && python src\api.py"
timeout /t 3 /nobreak >nul
echo.
echo Opening Web Interface...
start cortexdesk.html
echo.
echo Done! Backend running on http://127.0.0.1:8001
echo Press any key to exit this window...
pause >nul
